# Generated by Django 5.1.1 on 2024-10-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_addcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCourse',
        ),
    ]
